import { computeScore, type Report } from './types';

/**
 * A fabricated demonstration document. Clearly labelled as a sample everywhere
 * it is surfaced so nobody mistakes it for a real scan result.
 */
export function buildSampleReport(): Report {
  const findings: Report['findings'] = [
    {
      id: 'pdf-tags',
      title: 'Tagged PDF structure',
      status: 'critical',
      category: 'Structure',
      summary: 'No tag structure marker was found — the sample PDF appears to be untagged.',
      why: 'Tags carry headings, lists, tables, and reading order. Without them a screen reader receives one undifferentiated block of text, if it receives anything at all.',
      fix: 'Re-export from the source file with “Document structure tags for accessibility” enabled, or add tags in a remediation tool. Printing to PDF always discards tags.',
      details: [
        'A browser-based checker can only read the tag marker. Tag quality and PDF/UA conformance need a dedicated checker such as PAC or Acrobat’s full check.',
      ],
      refs: ['WCAG 1.3.1 Info and Relationships', 'PDF/UA-1'],
    },
    {
      id: 'pdf-text-layer',
      title: 'Selectable text layer',
      status: 'critical',
      category: 'Text',
      summary: '3 of 18 scanned pages contain images but no extractable text.',
      why: 'Where words are pixels rather than characters, screen readers, braille displays, search, and text reflow all fail.',
      fix: 'Run OCR on the affected pages and proofread the result, or replace the scanned pages with an export from the original source file.',
      locations: ['Page 4', 'Page 5', 'Page 12'],
      details: ['Image drawing operations observed: 27.'],
      refs: ['WCAG 1.1.1 Non-text Content', 'WCAG 1.4.5 Images of Text'],
    },
    {
      id: 'pdf-forms',
      title: 'Form fields have accessible labels',
      status: 'critical',
      category: 'Forms',
      summary: '5 of 9 form fields have no tooltip description.',
      why: 'A field without a description is announced only as “edit text”, leaving the person filling it in with no idea what to enter.',
      fix: 'In Acrobat, open Prepare Form and set the Tooltip of each field to its visible label. Confirm the tab order follows the visual order.',
      locations: ['Page 14 · dependent_dob_1', 'Page 14 · dependent_dob_2', 'Page 15 · signature_date', 'Page 15 · plan_code', 'Page 16 · consent_check'],
      refs: ['WCAG 1.3.1 Info and Relationships', 'WCAG 3.3.2 Labels or Instructions'],
    },
    {
      id: 'pdf-language',
      title: 'Document language',
      status: 'warning',
      category: 'Language',
      summary: 'No document language is declared in the catalog.',
      why: 'The declared language tells a screen reader which pronunciation rules and voice to use.',
      fix: 'Set the language in File → Properties → Advanced → Reading Options, or set it in the source document before exporting.',
      refs: ['WCAG 3.1.1 Language of Page'],
    },
    {
      id: 'pdf-links',
      title: 'Link annotations have readable text',
      status: 'warning',
      category: 'Links',
      summary: '4 of 11 links use generic wording or a bare URL.',
      why: 'Links are frequently read out of context in a list, so “click here” gives the listener nothing to choose from.',
      fix: 'Rewrite the visible link text to describe the destination, for example “Open the 2026 plan comparison chart”.',
      locations: ['Page 2 · click here', 'Page 7 · read more', 'Page 9 · https://example.org/benefits/2026/enrol…', 'Page 17 · here'],
      details: ['Link text is inferred from text near the annotation rectangle, so treat these as indicative.'],
      refs: ['WCAG 2.4.4 Link Purpose (In Context)'],
    },
    {
      id: 'pdf-bookmarks',
      title: 'Bookmarks for long documents',
      status: 'warning',
      category: 'Navigation',
      summary: 'No bookmarks were found in an 18-page document.',
      why: 'Bookmarks let keyboard and screen reader users jump between sections instead of paging through the file.',
      fix: 'Generate bookmarks from the source document’s heading styles on export, or add them in a PDF editor.',
      refs: ['WCAG 2.4.5 Multiple Ways'],
    },
    {
      id: 'pdf-reading-order',
      title: 'Reading order',
      status: 'review',
      category: 'Structure',
      summary: 'Reading order cannot be verified by this automated check.',
      why: 'Two-column layouts, callout boxes, and captions often read back in an order that does not match the page.',
      fix: 'Read the document with a screen reader, or use the reading-order tool in a PDF editor, and confirm the sequence.',
      refs: ['WCAG 1.3.2 Meaningful Sequence'],
    },
    {
      id: 'pdf-headings',
      title: 'Heading structure',
      status: 'review',
      category: 'Structure',
      summary: 'Heading levels cannot be read reliably from the browser.',
      why: 'Headings live in the tag tree. Large bold text is not a heading unless it is tagged as one.',
      fix: 'Check for H1–H6 tags in a logical order, or re-export from a source file that uses real heading styles.',
      refs: ['WCAG 1.3.1 Info and Relationships', 'WCAG 2.4.6 Headings and Labels'],
    },
    {
      id: 'pdf-contrast',
      title: 'Colour contrast and use of colour',
      status: 'review',
      category: 'Visual design',
      summary: 'Contrast ratios are not measured by this automated check.',
      why: 'Low-contrast text and colour-coded tables exclude people with low vision or colour vision deficiency.',
      fix: 'Confirm 4.5:1 for body text and 3:1 for large text, and add a second cue anywhere colour carries meaning.',
      refs: ['WCAG 1.4.3 Contrast (Minimum)', 'WCAG 1.4.1 Use of Color'],
    },
    {
      id: 'pdf-title',
      title: 'Document title in metadata',
      status: 'passed',
      category: 'Metadata',
      summary: 'A title is set: “2026 Benefits Enrollment Guide”.',
      why: 'Assistive technology announces the title when the document opens. Without it, users hear the file name.',
      fix: 'Confirm the viewer is set to show the document title rather than the file name in Initial View settings.',
      refs: ['WCAG 2.4.2 Page Titled'],
    },
    {
      id: 'pdf-permissions',
      title: 'Security settings allow assistive technology',
      status: 'passed',
      category: 'Security',
      summary: 'Content extraction for accessibility is permitted.',
      why: 'Some PDF security settings block text extraction entirely, which stops screen readers from reading the file.',
      fix: 'No action needed.',
      refs: ['WCAG 1.3.1 Info and Relationships'],
    },
  ];

  return {
    fileName: 'sample-benefits-enrollment-guide.pdf',
    fileSizeLabel: '2.4 MB',
    kind: 'PDF',
    generatedAt: new Date().toLocaleString(),
    isSample: true,
    score: computeScore(findings),
    facts: [
      { label: 'Format', value: 'Portable Document Format (.pdf)' },
      { label: 'Pages', value: '18' },
      { label: 'Pages scanned', value: '18' },
      { label: 'Tag marker', value: 'Absent' },
      { label: 'Characters', value: '41,802' },
      { label: 'Links', value: '11' },
      { label: 'Form fields', value: '9' },
      { label: 'Bookmarks', value: '0' },
    ],
    findings,
    parseNotes: ['This is a demonstration report built from fabricated data, not a scan of a real file.'],
  };
}
